#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
#include "images/garbage.h"
#include "images/man.h"
#include "images/startBack.h"
#include "images/BBB.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  PLAY,
  WIN,
  LOSE,
};
void gameBegin(enum gba_state *);
int lives = 3;
int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  videoBuffer[1208] = 0x7fff;
  // Save current and previous state of button input.  
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw
	waitForVBlank();

    switch (state) {
      case START:
        drawFullScreenImageDMA(startBack);
        drawString(95,80, "WELCOME PLAYER", WHITE);
        drawString(130, 80, "PRESS ENTER", RED);
        if(KEY_DOWN(BUTTON_START, currentButtons)) {
          state = PLAY;
        }
        break;
		
      case PLAY:

        // state = ?
		drawFullScreenImageDMA(BBB);
		gameBegin(&state);
		if (lives == 0) {
			state = LOSE;
		}
        break;
      case WIN:
	  drawFullScreenImageDMA(BBB);
	  drawString(95,80, "LEZ GO!", BLUE);
	  if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
		  lives = 3;
		  state = START;
	  }
        // state = ?
        break;
      case LOSE:
	  drawFullScreenImageDMA(BBB);
	  drawString(120, 50, "Unfortunately, you have lost. Try again!", RED);
	  if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
		  lives = 3;
		  state = START;
	  }

        // state = ?
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}


Goodman setupGoodman(void){
  Goodman g;
  g.row = 3;
  g.col = 50;
  g.w = 20;
  g.h = 20;
  drawImageDMA(g.row, g.col, g.w, g.h, man);
  drawRectDMA(0, 0, 40, 160, RED);
  drawRectDMA(80, 40, 40, 80, RED);
  drawRectDMA(120, 80 , 40, 40, RED);
  drawRectDMA(140, 120 , 40, 20, RED);
  
  drawRectDMA(0, 80, 40, 40, RED);
  drawRectDMA(0, 120, 40, 80, RED);
  drawRectDMA(0, 160, 40, 100, RED);
  drawRectDMA(0, 200, 40, 160, RED);
  drawString(1, 100, "lives: ", WHITE); 
  if(lives == 3) {
    drawString(1, 140, "3", WHITE);
  }
  if(lives == 2) {
    drawString(1, 140, "2", WHITE);
  }
  if(lives == 1) {
    drawString(1, 140, "1", WHITE);
  }
  if(lives == 0) {
    drawString(1, 140, "0", WHITE);
  }
  return g;
}
void gameBegin(enum gba_state *state) {
	Goodman g = setupGoodman();
	u32 currentButtons = BUTTONS;
  while (*state == PLAY) {
    waitForVBlank();
    currentButtons = BUTTONS;
    if(KEY_DOWN(BUTTON_UP, currentButtons)) {
		if((g.row <= 0 && (g.col >= 40 && g.col <= 60)) || (g.row <= 40 && (g.col >= 60 && g.col <= 100)) || (g.row <= 80 && (g.col >= 100 && g.col <= 140)) || (g.row <= 100 && (g.col >= 140 && g.col <= 180))) {
			lives--;
		    drawRectDMA(g.row, g.col, g.w, g.h, BLACK);
			g.row = g.row + 5;
		drawRectDMA(1, 140, 20, 20, RED);
		  if(lives == 3) {
			drawString(1, 140, "3", WHITE);
          }
          if(lives == 2) {
            drawString(1, 140, "2", WHITE);
          }
          if(lives == 1) {
            drawString(1, 140, "1", WHITE);
          }
          if(lives == 0) {
            drawString(1, 140, "0", WHITE);
            *state = LOSE;
            return;
          }
		}
		else {
			drawRectDMA(g.row, g.col, g.w, g.h, BLACK);
			g.row--;
		}
		drawImageDMA(g.row, g.col, g.w, g.h, man);
}
    if(KEY_DOWN(BUTTON_DOWN, currentButtons)) {
		if((g.row >= 60 && (g.col >= 40 && g.col <= 80)) || (g.row >= 100 && (g.col >= 80 && g.col <= 120)) || (g.row >= 120 && (g.col >= 120 && g.col <= 160))) {
			lives--;
			drawRectDMA(g.row, g.col, g.w, g.h, BLACK);
			g.row = g.row - 5;
			drawRectDMA(1, 140, 20, 20, RED);
		  if(lives == 3) {
			drawString(1, 140, "3", WHITE);
          }
          if(lives == 2) {
            drawString(1, 140, "2", WHITE);
          }
          if(lives == 1) {
            drawString(1, 140, "1", WHITE);
          }
          if(lives == 0) {
            drawString(1, 140, "0", WHITE);
            *state = LOSE;
            return;
          }
		}
		else {
			drawRectDMA(g.row, g.col, g.w, g.h, BLACK);
			g.row++;
		}
		drawImageDMA(g.row, g.col, g.w, g.h, man);
		if(g.row >= 140 && (g.col > 160)&& (g.col < 180)) {
        *state = WIN;
        return;
      }
		
}
if(KEY_DOWN(BUTTON_LEFT, currentButtons)) {
		if((g.col <= 40 && (g.row >= 0 && g.row <= 60)) || (g.col <= 80 && (g.row >= 60 && g.row <= 100)) || (g.col <= 120 && (g.row >= 100 && g.row <= 120)) || (g.col <= 160 && (g.row >= 120 && g.row <= 140))) {
			lives--;
		    drawRectDMA(g.row, g.col, g.w, g.h, BLACK);
			g.col = g.col + 5;
			g.col++;
			drawRectDMA(1, 140, 20, 20, RED);
		  if(lives == 3) {
			drawString(1, 140, "3", WHITE);
          }
          if(lives == 2) {
            drawString(1, 140, "2", WHITE);
          }
          if(lives == 1) {
            drawString(1, 140, "1", WHITE);
          }
          if(lives == 0) {
            drawString(1, 140, "0", WHITE);
            *state = LOSE;
            return;
          }
		}
		else {
			drawRectDMA(g.row, g.col, g.w, g.h, BLACK);
			g.col--;
		}
		drawImageDMA(g.row, g.col, g.w, g.h, man);
}
if(KEY_DOWN(BUTTON_RIGHT, currentButtons)) {
		if((g.col >= 60 && (g.row >= 0 && g.row <= 40)) || (g.col >= 100 && (g.row >= 40 && g.row <= 80)) || (g.col >= 140 && (g.row >= 80 && g.row <= 100)) || (g.col >= 180 && (g.row >= 100 && g.row <= 160))) {
			lives--;
			drawRectDMA(g.row, g.col, g.w, g.h, BLACK);
			g.col = g.col - 5;
			drawRectDMA(1, 140, 20, 20, RED);
		  if(lives == 3) {
			drawString(1, 140, "3", WHITE);
          }
          if(lives == 2) {
            drawString(1, 140, "2", WHITE);
          }
          if(lives == 1) {
            drawString(1, 140, "1", WHITE);
          }
          if(lives == 0) {
            drawString(1, 140, "0", WHITE);
            *state = LOSE;
            return;
          }
		}
		else {
			drawRectDMA(g.row, g.col, g.w, g.h, BLACK);
			g.col++;
		}
		drawImageDMA(g.row, g.col, g.w, g.h, man);
}
if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {      //return to start screen
        lives = 3;
        *state = START;
        return;
    }
  }
}